config/routes.rb
Rails.application.routes.draw do
  
  root to: 'calculators#new'
  get 'calculators/new', to: 'calculators#new'
  get 'calculators/result', to: 'calculators#result'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'calculators/result', to: 'calculators#result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculator.rb
class Calculator
    include ActiveModel::Model
    attr_accessor :ml
    attr_accessor :percent
    attr_accessor :weight #これを書かなかったらどうなるか
    validates :ml , presence: true
    validates :percent, presence: true
    validates :weight, presence: true
    #バリデーションはデータベースに保存するときだからいらないんじゃないか
end 
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  def new
    @calculator = Calculator.new
  end
  def result 
    @ml = params[:ml].to_i
    @percent = params[:percent].to_i / 100.to_f
    @weight = params[:weight].to_i
    @alcohol_gram = @ml * @percent * 0.8
    @times_to_breakdown = @weight * 0.1
    result = @alcohol_gram / @times_to_breakdown
    result_round = result.round(1)
    @result_hour = result_round.to_i
    @result_minitues = (result_round % 1 * 60).round
#結果が０になる時があるので解決しなければいけない?

  end 
  
  private

  def calculator_params
    params.require(:calculator).permit(:number)
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/new.html.slim
h1.mt-5　アルコール分解時間計算機

= form_with url: calculators_result_path do |f|
  .form-group
  = f.label :ml, '飲酒量（ml）'
  = f.number_field :ml,class:'form-control'
  .form-group
  = f.label :percent, '度数(%)'
  = f.number_field :percent,class:'form-control'
  .form-group
  = f.label :weight, '体重(kg)'
  = f.number_field :weight,class:'form-control'
  
  = f.submit '計算', class:'btn btn-primary mt-3'
  

.card.mt-5
  .card-default 
    p.text-center.text-secondary 計算結果

app/views/calculators/result.js.erb
<!--document.querySelector("#box").style.display = 'none';-->

var message = document.createElement('h2');
message.innerText = "アルコールが分解されるまでの時間は、約<%= @result_hour %>時間 <%= @result_minitues %>分です";
document.querySelector('p').insertAdjacentElement('afterend',message);

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Acalculator
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = yield